#############################################################################
# Makefile for building: Calculator.app/Contents/MacOS/Calculator
# Generated by qmake (3.1) (Qt 5.13.2)
# Project:  Calculator.pro
# Template: app
# Command: /Users/anazueva/Documents/5.13.2/clang_64/bin/qmake -o Makefile Calculator.pro -spec macx-clang CONFIG+=x86_64
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Documents/5.13.2/clang_64/lib/QtWidgets.framework/Headers -I../../Documents/5.13.2/clang_64/lib/QtGui.framework/Headers -I../../Documents/5.13.2/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Documents/5.13.2/clang_64/mkspecs/macx-clang -F/Users/anazueva/Documents/5.13.2/clang_64/lib
QMAKE         = /Users/anazueva/Documents/5.13.2/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/anazueva/Documents/5.13.2/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/anazueva/Documents/5.13.2/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Calculator1.0.0
DISTDIR = /Users/anazueva/Desktop/Calculator/.tmp/Calculator1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/anazueva/Documents/5.13.2/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/anazueva/Documents/5.13.2/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../../Documents/5.13.2/clang_64/mkspecs/features/spec_pre.prf \
		../../Documents/5.13.2/clang_64/mkspecs/qdevice.pri \
		../../Documents/5.13.2/clang_64/mkspecs/features/device_config.prf \
		../../Documents/5.13.2/clang_64/mkspecs/common/unix.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/mac.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/macx.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/sanitize.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/gcc-base.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/clang.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/clang-mac.conf \
		../../Documents/5.13.2/clang_64/mkspecs/qconfig.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/features/qt_functions.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/qt_config.prf \
		../../Documents/5.13.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Documents/5.13.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Documents/5.13.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/toolchain.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/default_pre.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/resolve_config.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/default_post.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/mac.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/warn_on.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/qt.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/resources.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/moc.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/uic.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/unix/thread.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/qmake_use.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/file_copies.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/rez.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/exceptions.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/yacc.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/lex.prf \
		Calculator.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = Calculator
DESTDIR       = 
TARGET        = Calculator.app/Contents/MacOS/Calculator

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15.1
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/anazueva/Desktop/Calculator/Calculator.pro


include /Users/anazueva/Documents/5.13.2/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Calculator.app/Contents/MacOS/Calculator: ui_mainwindow.h $(OBJECTS)  
	@test -d Calculator.app/Contents/MacOS/ || mkdir -p Calculator.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Calculator.pro ../../Documents/5.13.2/clang_64/mkspecs/macx-clang/qmake.conf ../../Documents/5.13.2/clang_64/mkspecs/features/spec_pre.prf \
		../../Documents/5.13.2/clang_64/mkspecs/qdevice.pri \
		../../Documents/5.13.2/clang_64/mkspecs/features/device_config.prf \
		../../Documents/5.13.2/clang_64/mkspecs/common/unix.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/mac.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/macx.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/sanitize.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/gcc-base.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/clang.conf \
		../../Documents/5.13.2/clang_64/mkspecs/common/clang-mac.conf \
		../../Documents/5.13.2/clang_64/mkspecs/qconfig.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Documents/5.13.2/clang_64/mkspecs/features/qt_functions.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/qt_config.prf \
		../../Documents/5.13.2/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Documents/5.13.2/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Documents/5.13.2/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/sdk.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/toolchain.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/default_pre.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/resolve_config.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/default_post.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/default_post.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/mac.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/warn_on.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/qt.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/resources.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/moc.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/unix/opengl.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/uic.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/unix/thread.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/qmake_use.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/file_copies.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/rez.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/testcase_targets.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/exceptions.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/yacc.prf \
		../../Documents/5.13.2/clang_64/mkspecs/features/lex.prf \
		Calculator.pro \
		../../Documents/5.13.2/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Documents/5.13.2/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Documents/5.13.2/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Calculator.pro -spec macx-clang CONFIG+=x86_64
../../Documents/5.13.2/clang_64/mkspecs/features/spec_pre.prf:
../../Documents/5.13.2/clang_64/mkspecs/qdevice.pri:
../../Documents/5.13.2/clang_64/mkspecs/features/device_config.prf:
../../Documents/5.13.2/clang_64/mkspecs/common/unix.conf:
../../Documents/5.13.2/clang_64/mkspecs/common/mac.conf:
../../Documents/5.13.2/clang_64/mkspecs/common/macx.conf:
../../Documents/5.13.2/clang_64/mkspecs/common/sanitize.conf:
../../Documents/5.13.2/clang_64/mkspecs/common/gcc-base.conf:
../../Documents/5.13.2/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Documents/5.13.2/clang_64/mkspecs/common/clang.conf:
../../Documents/5.13.2/clang_64/mkspecs/common/clang-mac.conf:
../../Documents/5.13.2/clang_64/mkspecs/qconfig.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Documents/5.13.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Documents/5.13.2/clang_64/mkspecs/features/qt_functions.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/qt_config.prf:
../../Documents/5.13.2/clang_64/mkspecs/macx-clang/qmake.conf:
../../Documents/5.13.2/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Documents/5.13.2/clang_64/mkspecs/features/exclusive_builds.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/mac/sdk.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/toolchain.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/mac/toolchain.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/default_pre.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/mac/default_pre.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/resolve_config.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/default_post.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/mac/default_post.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/mac/objective_c.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/mac/mac.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/warn_on.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/qt.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/resources.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/moc.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/unix/opengl.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/uic.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/unix/thread.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/qmake_use.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/file_copies.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/mac/rez.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/testcase_targets.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/exceptions.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/yacc.prf:
../../Documents/5.13.2/clang_64/mkspecs/features/lex.prf:
Calculator.pro:
../../Documents/5.13.2/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Documents/5.13.2/clang_64/lib/QtGui.framework/QtGui.prl:
../../Documents/5.13.2/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Calculator.pro -spec macx-clang CONFIG+=x86_64

qmake_all: FORCE

Calculator.app/Contents/PkgInfo: 
	@test -d Calculator.app/Contents || mkdir -p Calculator.app/Contents
	@$(DEL_FILE) Calculator.app/Contents/PkgInfo
	@echo "APPL????" > Calculator.app/Contents/PkgInfo
Calculator.app/Contents/Resources/empty.lproj: 
	@test -d Calculator.app/Contents/Resources || mkdir -p Calculator.app/Contents/Resources
	@touch Calculator.app/Contents/Resources/empty.lproj
	
Calculator.app/Contents/Info.plist: 
	@test -d Calculator.app/Contents || mkdir -p Calculator.app/Contents
	@$(DEL_FILE) Calculator.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.Calculator,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.Calculator,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,Calculator,g" -e "s,@LIBRARY@,Calculator,g" -e "s,\$${EXECUTABLE_NAME},Calculator,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../Documents/5.13.2/clang_64/mkspecs/macx-clang/Info.plist.app >Calculator.app/Contents/Info.plist

all: Makefile \
		Calculator.app/Contents/PkgInfo \
		Calculator.app/Contents/Resources/empty.lproj \
		Calculator.app/Contents/Info.plist Calculator.app/Contents/MacOS/Calculator

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Documents/5.13.2/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Calculator.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=x86_64

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Documents/5.13.2/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../../Documents/5.13.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../Documents/5.13.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Documents/5.13.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		moc_predefs.h \
		../../Documents/5.13.2/clang_64/bin/moc
	/Users/anazueva/Documents/5.13.2/clang_64/bin/moc $(DEFINES) --include /Users/anazueva/Desktop/Calculator/moc_predefs.h -I/Users/anazueva/Documents/5.13.2/clang_64/mkspecs/macx-clang -I/Users/anazueva/Desktop/Calculator -I/Users/anazueva/Documents/5.13.2/clang_64/lib/QtWidgets.framework/Headers -I/Users/anazueva/Documents/5.13.2/clang_64/lib/QtGui.framework/Headers -I/Users/anazueva/Documents/5.13.2/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -F/Users/anazueva/Documents/5.13.2/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../Documents/5.13.2/clang_64/bin/uic
	/Users/anazueva/Documents/5.13.2/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../Documents/5.13.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Documents/5.13.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../Documents/5.13.2/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Documents/5.13.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Documents/5.13.2/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Documents/5.13.2/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Calculator/bin || mkdir -p $(INSTALL_ROOT)/opt/Calculator/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app
	
	-$(QINSTALL) Calculator.app $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app
	-$(STRIP) $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Calculator/bin/Calculator.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Calculator/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

